sofiiiiii (2)/BariiLiii/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BariiLiii.Models;

namespace BariiLiii.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        //Home page
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Corona()
        {
            return View();
        }

        public IActionResult PlasticSurgery()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

sofiiiiii (2)/BariiLiii/Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BariiLiii.Data;
using BariiLiii.Models;
using BariiLiii.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;

namespace BariiLiii.Controllers
{
    public class PatientsController : Controller
    {
        private readonly BariiLiiiContext _context;
        private readonly Microsoft.AspNetCore.Identity.UserManager<BariiLiiiUser> _userManager;
        private readonly SignInManager<BariiLiiiUser> _signInManager;

        public PatientsController(BariiLiiiContext context,
            Microsoft.AspNetCore.Identity.UserManager<BariiLiiiUser> userManager,
            SignInManager<BariiLiiiUser> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        //Serach patiens
        public async Task<IActionResult> IndexAsync(string PatientId, string fullName, string Gender, string Location)
        {
            var searchPatients = from p in _context.Patients
                                 select p;

            if (!String.IsNullOrEmpty(PatientId))
            {
                searchPatients = searchPatients.Where(S => S.PatientId.Contains(PatientId));
            }

            if (!String.IsNullOrEmpty(fullName))
            {
                searchPatients = searchPatients.Where(S => S.FullName.Contains(fullName));
            }

            if (!String.IsNullOrEmpty(Gender))
            {
                searchPatients = searchPatients.Where(S => S.Gender.Contains(Gender));
            }

            if (!String.IsNullOrEmpty(Location))
            {
                searchPatients = searchPatients.Where(S => S.Location.Contains(Location));
            }

            return View(await searchPatients.ToListAsync());
        }

        // GET: Patients/Details/5
        public async Task<IActionResult> Details(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patient = await _context.Patients
                .FirstOrDefaultAsync(m => m.PatientId == id);
            if (patient == null)
            {
                return NotFound();
            }

            return View(patient);
        }

        // GET: Patients/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Patients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PatientId,FullName,Gender,Location")] Patient patient)
        {
            if (ModelState.IsValid)
            {
                _context.Add(patient);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(patient);
        }

        // GET: Patients/Edit/5
        public async Task<IActionResult> Edit(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patient = await _context.Patients.FindAsync(id);
            if (patient == null)
            {
                return NotFound();
            }
            return View(patient);
        }

        // POST: Patients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("PatientId,FullName,Gender,Location")] Patient patient)
        {
            if (id != patient.PatientId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(patient);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PatientExists(patient.PatientId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(patient);
        }

        // GET: Patients/Delete/5
        public async Task<IActionResult> Delete(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patient = await _context.Patients
                .FirstOrDefaultAsync(m => m.PatientId == id);
            if (patient == null)
            {
                return NotFound();
            }

            return View(patient);
        }

        // POST: Patients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var patient = await _context.Patients.FindAsync(id);
            _context.Patients.Remove(patient);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PatientExists(string id)
        {
            return _context.Patients.Any(e => e.PatientId == id);
        }
    }
}

sofiiiiii (2)/BariiLiii/Views/Home/Corona.cshtml
@{
    ViewData["Title"] = "Covid-19";
}
<h1>@ViewData["Title"]</h1>

<div class="card-deck">
    <div class="card">
        <img class="card-img-top" src="~/Images/coronavirus.jpg" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">What is Covid-19?</h5>
        </div>
        <div class="card-footer">
            <a href="#firstId" class="btn btn-primary">Click Here</a>
        </div>
    </div>
    <div class="card">
        <img class="card-img-top" src="~/Images/coronavirus-testing.jpg" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">Corona Test</h5>
        </div>
        <div class="card-footer">
            <a href="#secondId" class="btn btn-primary">Click Here</a>
        </div>
    </div>
    <div class="card">
        <img class="card-img-top" src="~/Images/trafficlightmodel.jpg" alt="Card image cap">
        <div class="card-body">
            <h5 class="Card title">The traffic Light Model</h5>
        </div>
        <div class="card-footer">
            <a href="#thirdId" class="btn btn-primary">Click Here</a>
        </div>
    </div>
</div>

@* Video *@
<div>
    <video class="mt-5 mx-auto" width="450" height="300" controls autoplay>
        <source src="~/Images/What Is Coronavirus (COVID-19)_.mp4" type="video/mp4">
    </video>
</div>

<div class="m-5 p-5 jumbotron" id="firstId">
    <div class="container">
        <div class="card-deck">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">What is Covid-19?</h3>
                    <p class="card-text">
                        Coronavirus disease (COVID-19) is an infectious disease caused by a newly discovered coronavirus.<br />
                        Most people infected with the COVID-19 virus will experience mild to moderate respiratory illness and recover without requiring special treatment.<br />
                        Older people, and those with underlying medical problems like cardiovascular disease, diabetes, chronic respiratory disease, and cancer are more likely to develop serious illness.<br />
                        The COVID-19 virus spreads primarily through droplets of saliva or discharge from the nose when an infected person coughs or sneezes, so it’s important that you also practice respiratory etiquette (for example, by coughing into a flexed elbow).<br />
                        <b>Symptoms</b> <br />
                        The most common symptoms of COVID-19 are fever, dry cough, and tiredness. <br />
                        Other symptoms that are less common and may affect some patients include loss of taste or smell, aches and pains, headache, sore throat, nasal congestion, red eyes, diarrhoea, or a skin rash.<br />
                        <b>What to do to keep yourself and others safe from COVID-19</b><br />
                        Maintain at least a 1-metre distance between yourself and others to reduce your risk of infection when they cough, sneeze or speak. Maintain an even greater distance between yourself and others when indoors. The further away, the better.<br />
                        Make wearing a mask a normal part of being around other people.<br />
                        clean your hands with an alcohol-based hand rub or wash them with soap and water.<br />
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="m-5 p-5 jumbotron" id="secondId">
    <div class="container">
        <div class="card-deck">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Corona Test</h3>
                    <p class="card-text">
                        Two kinds of tests are available for COVID-19:<br />
                        A <b>viral test</b> tells you if you have a current infection.<br />
                        An <b>antibody test</b> might tell you if you had a past infection.<br />
                        <b>Considerations for who should get tested</b><br />
                        People who have symptoms of COVID-19.<br />
                        People who have had close contact (within 6 feet for a total of 15 minutes or more) with someone with confirmed COVID-19.<br />
                        People who have been asked or referred to get testing by their healthcare provider, localexternal icon or state ​health department.<br />
                        Not everyone needs to be tested. If you do get tested, you should self-quarantine/isolate at home pending test results and follow the advice of your health care provider or a public health professional.<br />
                        <b>Results</b><br />
                        If you test positive, know what protective steps to take to prevent others from getting sick.<br />
                        If you test negative, you probably were not infected at the time your sample was collected. The test result only means that you did not have COVID-19 at the time of testing. Continue to take steps to protect yourself.<br />
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="m-5 p-5 jumbotron" id="thirdId">
    <div class="container">
        <div class="card-deck">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">The traffic Light Model</h3>
                    <p class="card-text">
                        This outline includes the imposition of restrictions for containing the spread of the coronavirus based on the classification of local authorities in Israel in four categories (red, orange, yellow and green).<br />
                        In accordance with the traffic light outline, customized assistance tools will be designed for each local authority with a view to educating the public, enforcing, building information systems, providing assistance in breaking the chains of infection and providing social assistance.<br />
                        According to the new outline, each local authority will be marked from 0 to 10 based on the following parameters:<br />
                        Number of new cases per week per 10,000 residents, percentage of positive test results per local authority per week and the growth rate of new cases in each local authority per week.<br />
                        Once every two weeks, based on each local authority's data average in the preceding week, this local authority's classification will be determined as follows:<br />
                        A local authority with an average mark over 7.5 will be classified as red area;<br />
                        A local authority with an average grade between 6 and 7.5 will be classified as an orange area;<br />
                        A local authority with an average grade between 4.5 and 6 will be classified as a yellow area;<br />
                        A local authority with an average grade below 4.5 will be classified as a green area.<br />
                    </p>
                    <p>
                        <h5>Gathering in Accordance with the Traffic Light Model</h5>
                        <b>In a "Red" Area</b><br />
                        The number of people will not exceed 20 people outdoors and 10 people indoors.<br />
                        <br />
                        <b>In an "Orange" Area</b><br />
                        Outdoors – Gatherings of up to 50 people<br />
                        In the outdoor area of a public or commercial establishment – No more than 40% the maximum permitted capacity according to this business' license.<br />
                        In case that this business' license contains no maximum capacity stipulations – no more than one person per 4 square meters and no more than 50 people in total.<br />
                        Indoors – Gatherings up to 25 people<br />
                        In the indoor area of a public or commercial establishment – No more than 20% the maximum permitted capacity according to this business' license.<br />
                        In case that this business' license contains no maximum capacity stipulations – no more than one person per 4 square meters and no more than 25 people in total.<br />
                        <br />
                        <b>In a "Yellow" Area</b><br />
                        Outdoors – Gatherings of up to 100 people<br />
                        In the outdoor area of a public or commercial establishment – No more than 60% the maximum permitted capacity according to this business' license.<br />
                        In case that this business' license contains no maximum capacity stipulations – no more than one person per 4 square meters and no more than 100 people in total.<br />
                        Indoors – Gatherings up to 50 people<br />
                        In the indoor area of a public or commercial establishment – No more than 40% the maximum permitted capacity according to this business' license.<br />
                        In case that this business' license contains no maximum capacity stipulations – no more than one person per 4 square meters and no more than 50 people in total.<br />
                        <br />
                        <b>In a "Green" Area</b><br />
                        Outdoors – Gatherings of up to 250 people<br />
                        In the outdoor area of a public or commercial establishment – No more than 80% the maximum permitted capacity according to this business' license.<br />
                        In case that this business' license contains no maximum capacity stipulations – no more than one person per 4 square meters and no more than 250 people in total.<br />
                        Indoors – Gatherings up to 100 people<br />
                        In the indoor area of a public or commercial establishment – No more than 60% the maximum permitted capacity according to this business' license.<br />
                        In case that this business' license contains no maximum capacity stipulations – no more than one person per 4 square meters and no more than 100 people in total.<br />
                    </p>
                    @* link to the traffic light model *@
                </div>
            </div>
        </div>
    </div>
</div>

sofiiiiii (2)/BariiLiii/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">BariLi</h1>
</div>

@*Choosing the department that the user needs*@
<div class="row">
    <div class="col-sm-6">
        <div class="card">
            <div class="card-body">
                <p><img src="~/Images/550_shutterstock_269923772.jpg" style=" height:250px;width:250px;" /></p>
                <h5 class="card-title">General Medicine</h5>
                <p class="card-text">For more information</p>
                <a href="#FirstId" class="btn btn-primary">Click Here</a>
            </div>
        </div>
    </div>

    <div class="col-sm-6">
        <div class="card">
            <div class="card-body">
                <p><img src="~/Images/plastic.jpg" style=" height:250px;width:250px;" /></p>
                <h5 class="card-title">Plastic Medicine</h5>
                <p class="card-text">For more information</p>
                <a href="#SecondId" class="btn btn-primary">Click Here</a>
            </div>
        </div>
    </div>
</div>

<div class="text-center">
    <h2 class="display-4">About Us</h2>
    <p>Established in 1983, for over 37 years, we have offered our patients the most advanced and effective cosmetic treatments, helping them achieve their desired results.</p>
    <p>Furthermore, we expertise in general medicine which include the most professional doctors.</p>
    <p>You can enjoy from our treatments and have the best experience.</p>
</div>

<aside class="text-center">
    <h2 class="display-4">Instructions for inviting an apointment</h2>
    <p>You have to regiter to our website.</p>
    <p>
        Then, you have to sign yourself in the
        <a asp-controller="Patients" asp-action="Create">PATIENTS TABLE</a>.
    </p>
    <p>Finally, you can enjoy from our treatments.</p>
</aside>

@* weather *@
<!-- weather widget start -->
<div id="m-booked-weather-bl250-49392"> 
    <div class="booked-wzs-250-175 weather-customize" style="background-color:#137AE9;width:160px;" id="width1">
        <div class="booked-wzs-250-175_in"> 
            <div class="booked-wzs-250-175-data"> 
                <div class="booked-wzs-250-175-left-img wrz-18"> 
                    <a target="_blank" href="https://www.booked.net/"> 
                        <img src="//s.bookcdn.com/images/letter/logo.gif" alt="booked.net" /> </a>
                </div> 
            <div class="booked-wzs-250-175-right"> 
                <div class="booked-wzs-day-deck"> 
                    <div class="booked-wzs-day-val"> 
                        <div class="booked-wzs-day-number">
                            <span class="plus">+</span>19
                        </div> 
                    <div class="booked-wzs-day-dergee"> 
                        <div class="booked-wzs-day-dergee-val">&deg;
                        </div> 
                        <div class="booked-wzs-day-dergee-name">C
                            </div> 
                    </div> 
                    </div> 
                <div class="booked-wzs-day"> 
                    <div class="booked-wzs-day-d">H: 
                        <span class="plus">+</span>21&deg;
                    </div> 
                    <div class="booked-wzs-day-n">L: 
                        <span class="plus">+</span>15&deg;
                    </div> 
                </div> 
                </div> 
                <div class="booked-wzs-250-175-info"> 
                    <div class="booked-wzs-250-175-city">Ge'ullim 
                    </div> 
                    <div class="booked-wzs-250-175-date">Sunday, 08 November</div> 
                        <div class="booked-wzs-left"> 
                            <span class="booked-wzs-bottom-l">See 7-Day Forecast</span> 
                        </div> 
                </div> 
            </div> 
        </div> 
        <a target="_blank" href="https://www.booked.net/weather/ge-ullim-546405"> 
            <table cellpadding="0" cellspacing="0" class="booked-wzs-table-250"> 
            <tr> 
                <td>Mon</td> 
                <td>Tue</td> 
                <td>Wed</td> 
                <td>Thu</td> 
                <td>Fri</td> 
                <td>Sat</td> 
            </tr> 
            <tr> 
                <td class="week-day-ico">
                    <div class="wrz-sml wrzs-18">
                    </div>
                </td> 
                <td class="week-day-ico">
                    <div class="wrz-sml wrzs-01">
                    </div>
                </td>
                <td class="week-day-ico">
                    <div class="wrz-sml wrzs-01">
                    </div>
                </td> 
                <td class="week-day-ico">
                    <div class="wrz-sml wrzs-01">
                    </div>
                </td> 
                <td class="week-day-ico">
                    <div class="wrz-sml wrzs-01">
                    </div>
                </td> 
                <td class="week-day-ico">
                    <div class="wrz-sml wrzs-01">
                    </div>
                </td>
            </tr> 
            <tr> 
                <td class="week-day-val">
                    <span class="plus">+</span>20&deg;
                </td> 
                <td class="week-day-val">
                    <span class="plus">+</span>21&deg;
                </td> 
                <td class="week-day-val">
                    <span class="plus">+</span>20&deg;
                </td> 
                <td class="week-day-val">
                    <span class="plus">+</span>21&deg;
                </td> 
                <td class="week-day-val">
                    <span class="plus">+</span>22&deg;
                </td> 
                <td class="week-day-val">
                    <span class="plus">+</span>21&deg;
                </td>
            </tr> 
            <tr> 
                <td class="week-day-val">
                    <span class="plus">+</span>13&deg;
                </td> 
                <td class="week-day-val">
                    <span class="plus">+</span>14&deg;
                </td> 
                <td class="week-day-val">
                    <span class="plus">+</span>14&deg;
                </td> <td class="week-day-val">
                    <span class="plus">+</span>13&deg;
                </td> 
                <td class="week-day-val">
                    <span class="plus">+</span>14&deg;
                </td> 
                <td class="week-day-val">
                    <span class="plus">+</span>14&deg;
                </td> 
            </tr>
        </table> 
        </a> 
        </div>
    </div> 
</div>

<script type="text/javascript">var css_file = document.createElement("link");
    css_file.setAttribute("rel", "stylesheet");
    css_file.setAttribute("type", "text/css");
    css_file.setAttribute("href", 'https://s.bookcdn.com/css/w/booked-wzs-widget-275.css?v=0.0.1');
    document.getElementsByTagName("head")[0].appendChild(css_file);
    function setWidgetData(data) {
        if (typeof (data) != 'undefined' && data.results.length > 0)
        {
            for (var i = 0; i < data.results.length; ++i)
            {
                var objMainBlock = document.getElementById('m-booked-weather-bl250-49392');
                if (objMainBlock !== null)
                {
                    var copyBlock = document.getElementById('m-bookew-weather-copy-' + data.results[i].widget_type);
                    objMainBlock.innerHTML = data.results[i].html_code;
                    if (copyBlock !== null)
                        objMainBlock.appendChild(copyBlock);
                }
            }
        } else {
            alert('data=undefined||data.results is empty');
        }
    }</script>
<script type="text/javascript" charset="UTF-8" src="https://widgets.booked.net/weather/info?action=get_weather_info&ver=6&cityID=546405&type=3&scode=124&ltid=3457&domid=w209&anc_id=84341&cmetric=1&wlangID=1&color=137AE9&wwidth=160&header_color=ffffff&text_color=333333&link_color=08488D&border_form=1&footer_color=ffffff&footer_text_color=333333&transparent=0"></script>
<!-- weather widget end -->



@*Go down to General medicine*@
<div class="m-5 p-5 jumbotron" id="FirstId">
    <div class="container">
        <h2 class="display-4">General Medicine</h2>
        <div class="card-deck">
            <div class="card">
                <div class="card-body">
                    <p><img src="" style=" height:250px;width:250px;" /></p>
                    <h5 class="card-title">About our general medical team</h5>
                </div>
                <div class="card-footer">
                    <a href="#" class="btn btn-primary">Click Here</a>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <p><img src="" style=" height:250px;width:250px;" /></p>
                    <h5 class="card-title">Covid-19</h5>
                </div>
                <div class="card-footer">
                    @* Sending to the relevant page *@
                    <form asp-controller="Home" asp-action="Corona" method="get">
                        <button type="submit" class="btn btn-outline-primary" name="info" value="Corona">
                            Click Here
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@*Go down to Plastic medicine*@
<div class="m-5 p-5 jumbotron" id="SecondId">
    <div class="container">
        <h2 class="display-4">Plastic Medicine</h2>
        <div class="card-deck">
            <div class="card">
                <div class="card-body">
                    <p><img src="" style=" height:250px;width:250px;" /></p>
                    <h5 class="card-title">About our plastic medical team</h5>
                </div>
                <div class="card-footer">
                    <a href="#" class="btn btn-primary">Click Here</a>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <p><img src="" style=" height:250px;width:250px;" /></p>
                    <h5 class="card-title">Plastic surgery</h5>
                </div>
                <div class="card-footer">
                    @* Sending to the relevant page *@
                    <form asp-controller="Home" asp-action="PlasticSurgery" method="get">
                        <button type="submit" class="btn btn-outline-primary" name="info" value="PlasticSurgery">
                            Click Here
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>